### PR TITLE
switch to yeslogic-fontconfig-sys instead of servo-fontconfig

### PR DESCRIPTION
**Pull request by Be-ing**
servo-fontconfig statically links a vendored fontconfig library if fontconfig is not found by pkgconfig. Using a vendored fontconfig
library instead of the system fontconfig library doesn't actually work well though:
https://github.com/slint-ui/slint/issues/88
Building a vendored copy of fontconfig is also problematic because fontconfig has a lot of C dependencies, which makes it difficult to cross compile the vendored copy of fontconfig:

```
$ pkg-config fontconfig --static --libs
-lfontconfig -lfreetype -lz -lbz2 -lpng16 -lm -lm -lz -lharfbuzz -lm -lglib-2.0 -lm -lpcre -lsysprof-capture-4 -pthread -lgraphite2 -lbrotlidec -lbrotlicommon -lxml2 -lz -llzma -lm
```

Instead of using a vendored copy, with
https://github.com/yeslogic/fontconfig-rs/pull/12
yeslogic-fontconfig-sys will have a Cargo feature to dlopen fontconfig at runtime instead of linking it at build time. This is exposed in font-kit with the new source-fontconfig-dlopen feature, which is disabled by default. This feature makes it considerably easier to cross compile by avoiding the need to cross compile fontconfig and all its dependencies.

### CODE REVIEW

**Comment by Be-ing** [comment]
This is a draft until https://github.com/yeslogic/fontconfig-rs/pull/12 is merged upstream.

**Comment by Be-ing** [comment]
See also:
https://github.com/servo/libfontconfig/issues/65
https://github.com/yeslogic/fontconfig-rs/issues/11

Having two different -sys crates for fontconfig has created a messy situation because Cargo will refuse to build if two -sys crates link the same library by specifying `link = "fontconfig"` in Cargo.toml. It would be great if we could converge on one and deprecate the other. If you agree to drop servo-fontconfig, I'd be happy to make pull request's for servo-fontconfig's other reverse dependencies.

**Comment by Be-ing** [comment]
PR to switch Slint to yeslogic-fontconfig-sys from servo-fontconfig: https://github.com/slint-ui/slint/pull/956

**Comment by Be-ing** [comment]
> This is a draft until https://github.com/yeslogic/fontconfig-rs/pull/12 is merged upstream.

That was merged and released upstream. This is ready for review.

**Comment by jdm** [comment]
This seems like a reasonable path forwards. Thanks!
@bors-servo r+

**Comment by jdm** [comment]
Can you run `cargo fmt`?

**Comment by Be-ing** [comment]
Okay, I ran `cargo fmt`.

**Comment by Be-ing** [comment]
Thanks for merging. Could you publish a new release of the crate?

**Comment by jdm** [comment]
Done.

**Pull request merged**
