### PR TITLE
Update to version 0.12 in preparation for release

### PR DESCRIPTION
**Pull request by mrobinson**

### CODE REVIEW

**Comment by jayvdb** [comment]
What is the next step here? Who can r+ it ? ;-)

**Review by mukilan — APPROVED** [review]

**Comment by mrobinson** [comment]
The new version of the crate should be published now.

**Comment by jayvdb** [comment]
Lovely. Thank you!

**Comment by jayvdb** [comment]
fyi when I update the version for https://crates.io/crates/plotters and run their tests, I dont get compile issues - I get:
```
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/home/jayvdb/rust/plotters/target/debug/deps/plotters-14ec6df465028332` (signal: 11, SIGSEGV: invalid memory reference)
```
will update here when I figure out what is going on

**Comment by jayvdb** [comment]
Created https://github.com/servo/font-kit/issues/224

**Pull request merged**
