### PR TITLE
Update lyon_path to 0.15

### PR DESCRIPTION
**Pull request by Eijebong**
Tests are failing locally but it might be some font related stuff that would only pass on CI

### CODE REVIEW

**Comment by RazrFalcon** [comment]
I've fixed the master branch, but your PR is still fails.

**Comment by Eijebong** [comment]
There, should be good now,  rebased and ran rustfmt

**Comment by RazrFalcon** [comment]
Looks like @pcwalton should look into this.

**Comment by pcwalton** [comment]
On it

**Pull request merged**
